version: "3"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    # environment:
    # - MONGODB_USER=bube
    # - MONGODB_DATABASE=test_db
    # - MONGODB_PASS=password
    volumes:
      - ./.data/mongodb:/data/db
    command: mongod --bind_ip_all

# Add VOlume for redis
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  nodeapp:
    image: nodeapp
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - redis
      - mongo
    env_file: ./.env
    links:
      - mongo
      - redis
  busybox:
    image: busybox
    command: top

